application: my-pager
version: test
runtime: go
api_version: go1

handlers:
- url: /admin(|.*)
  script: _go_app
  login: admin
  secure: always
- url: /.*
  script: _go_app

inbound_services:
- mail
